// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a2c7e41-6782-4f91-8d2a-190f03225c5a"),
                            CreatedAt = new DateTime(2026, 2, 1, 18, 17, 14, 608, DateTimeKind.Utc).AddTicks(2350),
                            Description = "Science-backed skincare designed to enhance your natural glow with vegan formulas.",
                            IsDeleted = false,
                            LogoUrl = "https://placehold.co/400x400?text=Lumina+Aesthetics",
                            Name = "Lumina Aesthetics",
                            Slug = "lumina-aesthetics",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3d9f1028-e522-4a7b-bba1-ec6829731d14"),
                            CreatedAt = new DateTime(2026, 2, 1, 18, 17, 14, 608, DateTimeKind.Utc).AddTicks(2920),
                            Description = "High-performance athletic apparel specializing in moisture-wicking fabrics for runners.",
                            IsDeleted = false,
                            LogoUrl = "https://placehold.co/400x400?text=Velocity+Gear",
                            Name = "Velocity Gear",
                            Slug = "velocity-gear",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c94b3a12-88ef-4c8d-905e-f7893122709e"),
                            CreatedAt = new DateTime(2026, 2, 1, 18, 17, 14, 608, DateTimeKind.Utc).AddTicks(2930),
                            Description = "Artisanal coffee roastery sourcing organic, fair-trade beans from around the globe.",
                            IsDeleted = false,
                            LogoUrl = "https://placehold.co/400x400?text=Hearth+%26+Bean",
                            Name = "Hearth & Bean",
                            Slug = "hearth-bean",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1b7c2d3-a4e5-4f67-8901-23456789ab01"),
                            CreatedAt = new DateTime(2026, 2, 3, 22, 1, 0, 0, DateTimeKind.Utc),
                            Description = "Modern, minimalist water brand committed to purity and sustainable hydration.",
                            IsDeleted = false,
                            LogoUrl = "/images/brands/aquavital.png",
                            Name = "AquaVital",
                            Slug = "aquavital",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1b7c2d3-a4e5-4f67-8901-23456789ab02"),
                            CreatedAt = new DateTime(2026, 2, 3, 22, 1, 0, 0, DateTimeKind.Utc),
                            Description = "Futuristic electronics brand pushing the boundaries of technical innovation.",
                            IsDeleted = false,
                            LogoUrl = "/images/brands/zenith_electronics.png",
                            Name = "Zenith Electronics",
                            Slug = "zenith-electronics",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1b7c2d3-a4e5-4f67-8901-23456789ab03"),
                            CreatedAt = new DateTime(2026, 2, 3, 22, 1, 0, 0, DateTimeKind.Utc),
                            Description = "Organic, earthy food products sourced from natural and wholesome origins.",
                            IsDeleted = false,
                            LogoUrl = "/images/brands/terra_foods.png",
                            Name = "Terra Foods",
                            Slug = "terra-foods",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1b7c2d3-a4e5-4f67-8901-23456789ab04"),
                            CreatedAt = new DateTime(2026, 2, 3, 22, 1, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant and chic fashion brand featuring contemporary luxury apparel.",
                            IsDeleted = false,
                            LogoUrl = "/images/brands/nova_fashion.png",
                            Name = "Nova Fashion",
                            Slug = "nova-fashion",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1b7c2d3-a4e5-4f67-8901-23456789ab05"),
                            CreatedAt = new DateTime(2026, 2, 3, 22, 1, 0, 0, DateTimeKind.Utc),
                            Description = "Dynamic fitness brand providing energizing and powerful athletic gear.",
                            IsDeleted = false,
                            LogoUrl = "/images/brands/pulse_fitness.png",
                            Name = "Pulse Fitness",
                            Slug = "pulse-fitness",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1b7c2d3-a4e5-4f67-8901-23456789ab06"),
                            CreatedAt = new DateTime(2026, 2, 3, 22, 1, 0, 0, DateTimeKind.Utc),
                            Description = "Cozy and modern home goods designed for contemporary living spaces.",
                            IsDeleted = false,
                            LogoUrl = "/images/brands/echo_home.png",
                            Name = "Echo Home",
                            Slug = "echo-home",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1b7c2d3-a4e5-4f67-8901-23456789ab07"),
                            CreatedAt = new DateTime(2026, 2, 3, 22, 1, 0, 0, DateTimeKind.Utc),
                            Description = "Sharp and technical eyewear brand focused on precision and modern style.",
                            IsDeleted = false,
                            LogoUrl = "/images/brands/prism_optics.png",
                            Name = "Prism Optics",
                            Slug = "prism-optics",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1b7c2d3-a4e5-4f67-8901-23456789ab08"),
                            CreatedAt = new DateTime(2026, 2, 3, 22, 1, 0, 0, DateTimeKind.Utc),
                            Description = "Calming health and wellness products inspired by natural zen and tranquility.",
                            IsDeleted = false,
                            LogoUrl = "/images/brands/sage_wellness.png",
                            Name = "Sage Wellness",
                            Slug = "sage-wellness",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1b7c2d3-a4e5-4f67-8901-23456789ab09"),
                            CreatedAt = new DateTime(2026, 2, 3, 22, 1, 0, 0, DateTimeKind.Utc),
                            Description = "High-tech electric vehicle brand leading the way in sustainable innovation.",
                            IsDeleted = false,
                            LogoUrl = "/images/brands/volt_motors.png",
                            Name = "Volt Motors",
                            Slug = "volt-motors",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1b7c2d3-a4e5-4f67-8901-23456789ab10"),
                            CreatedAt = new DateTime(2026, 2, 3, 22, 1, 0, 0, DateTimeKind.Utc),
                            Description = "Sophisticated software company delivering reliable and advanced technological solutions.",
                            IsDeleted = false,
                            LogoUrl = "/images/brands/orion_tech.png",
                            Name = "Orion Tech",
                            Slug = "orion-tech",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5c60f693-befd-460e-8d59-39322f43732c"),
                            CreatedAt = new DateTime(2026, 2, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Products for maintaining and styling hair.",
                            IsDeleted = false,
                            Name = "Hair Care",
                            Slug = "hair-care",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            CreatedAt = new DateTime(2026, 2, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Products for skin health and beauty.",
                            IsDeleted = false,
                            Name = "Skin Care",
                            Slug = "skin-care",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1d9e902b-270c-4389-b8a1-d4567890abcd"),
                            CreatedAt = new DateTime(2026, 2, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Products for beard grooming and maintenance.",
                            IsDeleted = false,
                            Name = "Beard Care",
                            Slug = "beard-care",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewEmailCandidate")
                        .HasColumnType("text");

                    b.Property<string>("NewEmailCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NewEmailCodeExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PreviousRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PreviousRefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledDeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerificationCodeExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationPurpose")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "62562217-0941-4566-9626-41bf75058097",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "61026071-7443-4418-971c-308235210145",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "d3278993-9076-4d56-aff5-f2619da05697",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
